### ISSUE TITLE
Question about dust opcode and kr chnget

### ISSUE THREAD

**Issue by boonier** [rorywalsh/csoundo#4]
Sorry to misappropriate the Issues tab as support, but I wasn't sure where to post this, but it is csoundo related I guess?

I'm using the dust opcode and I want to visualise the impulses in Processing. Problem is that 60fps is not granular enough to catch them on the Processing side in the draw loop. 

I've played with setting the ksmps to a value equal to 60fps (roughly), but no dice. What's the best way to ensure that this kind of detail gets across?

cheers

**Comment by boonier** [comment]
It's preferable from an audio pov to use dust at audio rate and downsample.

Two different approaches I've tried:

```
instr 2
	iamp 		= 0.5
	krate		= 2
	aDust 	dust 1, krate
	kDust 	downsamp aDust
			chnset ceil:k(kDust), "klipout"
			outs aDust*iamp, aDust*iamp
endin

instr 3
	iamp 		= 0.5
	krate		= 3
	kDust 	dust 1, krate
			chnset ceil:k(kDust), "klipout"
	aDust 	upsamp kDust
			outs aDust*iamp, aDust*iamp
endin
```

**Comment by boonier** [comment]
@rorywalsh Actually finding that using Processing to issue events to Csound is more reliable . Creating the dust sound using the mpulse opcode works great :)

**Comment by rorywalsh** [comment]
Hi @boonier , sorry for the latest reply. I somehow missed the notifications. I think driving the visuals from the audio side will always result in better synchronisation, but as you've seen, the frame rate on the visual side isn't anywhere near as high-res as the audio. I don't think there is a one-size-fits-all solution. By the sounds of it, you got it sorted? Btw, please feel free to post questions on the Csound [Cabbage](http://forum.cabbageaudio.com/) list, we have a forum their for Csound and games, similar questions pop up all the time. Feel free to close this if you got everything sorted.

**Comment by boonier** [comment]
Cool yep thanks @rorywalsh
